#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""色の登録簿から**予備の材質表**を焼く（`hd2d/render/material_table.inc`）。

## これは予備の道である（**正はプレハブの宣言**）

2026-08-23 に材質の出どころを変えた（決めたこと:「パレットの色で汚しを入れるのを
やめよう。パレットの共有もやめて、ベースのパレットのコピーを作り個別に使うように」）。

  * **正** … `tools/voxel/gen_prefabs.py` が `.jsonc` の `palette` へ**材質を焼く**。
    読む側は `hd2d/voxel/prefab.cpp`（`.vox` の色と照合し、食い違えば宣言ごと捨てる）
  * **予備** … ここで焼く「色 → 材質」。**宣言の無い物だけ**に効く
    （手で作った `.vox`・目録に無いプレハブ・C++ で組んだ箱）

パレットはライブラリじゅうで色を使い回しているので、**色は材を指さない**——同じ灰色が
切石にも鉛板にもなる。予備の道は「何も分からないよりまし」の位置づけで、
ここの精度を上げることに時間を使わないこと（直すなら宣言の側）。

判断そのもの（名前・註釈 → 材質）は `tools/voxel/palette_materials.py` に 1 か所だけ置く。

## 使い方

    python tools/voxel/gen_material_table.py            # 焼く
    python tools/voxel/gen_material_table.py --report   # 分類の内訳だけ出す（焼かない）
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'hd2d' / 'render' / 'material_table.inc'

_spec = importlib.util.spec_from_file_location(
    'palette_materials', str(ROOT / 'tools' / 'voxel' / 'palette_materials.py'))
pm = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(pm)

#: 判断は `palette_materials.py` にしかない（宣言と予備表で割らないため）。
CLASSES = pm.CLASSES
classify = pm.classify


def load_registry():
    """`gen_prefabs.py` を**読み込むだけ**で登録簿を借りる（生成は走らない）。"""
    path = ROOT / 'tools' / 'voxel' / 'gen_prefabs.py'
    spec = importlib.util.spec_from_file_location('gen_prefabs_registry', path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)   # `if __name__ == '__main__'` で守られている
    return module.C, module.PAL


def build():
    names, pal = load_registry()
    #: RGB → (材質, 名前)。同じ色に別の名前が付いていたら**先に登録したほうを採る**。
    table = {}
    clash = []
    for name, index in sorted(names.items(), key=lambda kv: kv[1]):
        rgb = pal.get(index)
        if rgb is None:
            continue
        key = (rgb[0] << 16) | (rgb[1] << 8) | rgb[2]
        cls = classify(name)
        if key in table:
            if table[key][0] != cls:
                clash.append((name, table[key][1], cls))
            continue
        table[key] = (cls, name)
    return table, clash


def main(argv=None):
    ap = argparse.ArgumentParser(description='色の登録簿から予備の材質表を焼く')
    ap.add_argument('--report', action='store_true', help='内訳だけ出す（焼かない）')
    args = ap.parse_args(argv)

    table, clash = build()
    tally = {cls: 0 for cls in CLASSES}
    for cls, _name in table.values():
        tally[cls] += 1
    print('色 {} 件'.format(len(table)))
    for cls in CLASSES:
        print('  {:<8} {:>4}'.format(cls, tally[cls]))
    if tally['Default']:
        rest = [n for c, n in table.values() if c == 'Default']
        print('  分類できなかった色: ' + ' '.join(sorted(rest)))
    for name, other, cls in clash:
        print('  同じ RGB で食い違い: {} ({}) と {}'.format(name, cls, other))
    if args.report:
        return 0

    lines = [
        '// generated by tools/voxel/gen_material_table.py -- do not edit by hand.',
        '// Fallback only: a prefab .jsonc declares its own palette materials.',
        '// key = 0xRRGGBB of a palette entry, value = MaterialClass (surface_wear.h).',
        '',
    ]
    for key in sorted(table):
        cls, name = table[key]
        lines.append('{{ 0x{:06X}u, {} }}, // {} ({})'.format(key, CLASSES.index(cls), name, cls))
    #: 改行は LF で書く（記憶 `hengband-python-edit-flips-line-endings`）。
    OUT.write_bytes(('\n'.join(lines) + '\n').encode('ascii'))
    print('焼いた: {} ({} 件)'.format(OUT.relative_to(ROOT), len(table)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
